apiVersion: v1
kind: Namespace
metadata:
  name: party-cluster
  labels:
    app.kubernetes.io/name: party-cluster
    app.kubernetes.io/instance: party-cluster
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/part-of: party-cluster
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node
  namespace: party-cluster
  labels:
    app.kubernetes.io/name: party-cluster
    app.kubernetes.io/instance: party-cluster
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/part-of: party-cluster
    app.kubernetes.io/component: node
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/component: node
      app.kubernetes.io/part-of: party-cluster
  template:
    metadata:
      labels:
        app.kubernetes.io/component: node
        app.kubernetes.io/part-of: party-cluster
    spec:
      containers:
        - name: node
          image: party-cluster/node:dev
          command: ["uvicorn", "cluster.node.api:app", "--reload", "--host", "0.0.0.0", "--port", "8888"]
          ports:
            - containerPort: 8888
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: CLUSTER_HOSTNAME
              value: "party-cluster"
---
apiVersion: v1
kind: Service
metadata:
  name: party-cluster
  namespace: party-cluster
  labels:
    app.kubernetes.io/part-of: party-cluster
    app.kubernetes.io/component: node
spec:
  type: ClusterIP
  clusterIP: None  # "clusterIP: None" makes this service a headless which is crutial for the peer discovery
  selector:
    app.kubernetes.io/part-of: party-cluster
    app.kubernetes.io/component: node
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
---
# A regular ClusterIP service to be able to send HTTP requests to the cluster's nodes
apiVersion: v1
kind: Service
metadata:
  name: node
  namespace: party-cluster
  labels:
    app.kubernetes.io/part-of: party-cluster
    app.kubernetes.io/component: node
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/part-of: party-cluster
    app.kubernetes.io/component: node
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
