docker_build(
    'party-cluster/node:dev',
    context='.',
    dockerfile='./Dockerfile',
    live_update=[
        sync('./cluster/', '/src/cluster/'),
        run('pip install -r requirements.txt', trigger=['requirements.txt']),
    ],
    match_in_env_vars=True,
)

k8s_yaml('deployment.yaml')

k8s_resource(
    'node',
    labels=['party-cluster'],
    port_forwards=["8888:8888"]
)
